### PR TITLE
Introduces custom tab completion callbacks

### PR DESCRIPTION
**Pull request by LiquidityC**
Fixes: #335

### CODE REVIEW

**Comment by Xandaros** [comment]
Do you return the entire prompt, or just the last word?
Say I type in `/connect asd` and possible completions are `/connect asdfgh` and `/connect asdjkl` - should the function return `["asdfgh", "asdjkl"]` or `["/connect asdfgh", "/connect asdjkl"]`?
The docs mention word, but the example is only one word long, so I'm not sure.

Also, there are roughly two philosophies with completion. I personally prefer if it only completes unambiguous input (so you have to type in `/connect asdf` to complete to `/connect asdfgh`). If the input is ambiguous, it would print possible options.
I think this is better, especially if there are a lot of options - but this behaviour does not seem possible with the current implementation.
Maybe this could be added later as a setting?

**Comment by LiquidityC** [comment]
That's right. The existing implementation works on just single word completion. I was also thinking about this during implementation. I'm planning on solving this. Either through two arguments to the callback, eg. Word and full line. Alternatively adding a method to retrieve the current prompt buffer through a secondary function. I'll decide once I know what's easier. I'm guessing that will be option one. The script module has very little knowledge of the outside world within the application.

**Comment by LiquidityC** [comment]
Actually. My mistake. The completion callback receives the entire promptline. Hitting tab on the prompt `/connect some` will send `/connect some` as the input argument to the completion callback. So that already works the way we want it to. I need to update the documentation to explain this though.

I'll send an other commit to this PR when I get some time later.

In regards to ambiguity. Yes we could extend that further down the line it won't be critical or require modifications in this PR. It should be possible to introduce a setting to alter this behavior.

**Comment by Xandaros** [comment]
Ok, good. You had me worried there :D
Not having the context of the entire line would be... suboptimal.

But yeah, the completion behaviour I personally want won't be possible with this, but it's a very good start.

**Review by Xandaros — APPROVED** [review]

**Pull request merged**
